### ISSUE TITLE
Remove RFN, rename License file, use canonical style copyright notice

### ISSUE THREAD

**Issue by davelab6** [shahabsiavash/KayKhosrow-Font#1]
I'd like to suggest removing the RFN (seen [here](https://github.com/shahabsiavash/KayKhosrow-Font/blob/4f53c3e1b365f4662e32ab51c389858713b08ab3/Licence#L5) and updating the copyright notice to be more 'canonical,' and renaming the file to `OFL.txt`

Please see https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md#ofltxt for details

**Comment by shahabsiavash** [comment]
Thanks. I changed the license file.

**Comment by davelab6** [comment]
Perfect! Please close :)

**Comment by shahabsiavash** [comment]
Sure :)
